# Bosun Audit GitHub Action
#
# This workflow runs Bosun audits on pull requests and pushes.
#
# Installation:
#   1. Copy this file to your project: .github/workflows/bosun-audit.yml
#   2. Ensure Bosun is installed as a plugin in your project
#   3. Adjust the audit scope and triggers as needed
#
# Requirements:
#   - Claude Code CLI must be available (actions will install if needed)
#   - ANTHROPIC_API_KEY secret must be set in repository settings

name: Bosun Audit

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      scope:
        description: 'Audit scope'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - security
          - quality
          - docs

# Cancel in-progress runs for the same PR
concurrency:
  group: bosun-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    name: Run Bosun Audit
    runs-on: ubuntu-latest
    # Only run if API key is available
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Claude Code CLI (adjust based on actual installation method)
      - name: Install Claude Code
        run: |
          # Install Claude Code CLI
          # Note: Update this command based on official installation instructions
          npm install -g @anthropic-ai/claude-code || true
          echo "Claude Code installation attempted"

      # Run pre-commit checks (lightweight, no API needed)
      - name: Run pre-commit checks
        run: |
          # Secret detection
          echo "Checking for secrets in changed files..."

          # Get changed files
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || git ls-files)
          fi

          ERRORS=0

          # Check for common secret patterns
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              # Skip binary files and lock files
              if file "$file" | grep -q "text"; then
                if grep -qE "(API[_-]?KEY|SECRET|PASSWORD|PRIVATE[_-]?KEY)\s*[:=]\s*['\"][^'\"]{8,}" "$file" 2>/dev/null; then
                  echo "::warning file=$file::Potential secret detected"
                fi
              fi
            fi
          done

          # Check for sensitive files
          for file in $CHANGED_FILES; do
            case "$file" in
              *.env|*.pem|*.key|*credentials*|*secrets*)
                echo "::error file=$file::Sensitive file should not be committed"
                ERRORS=$((ERRORS + 1))
                ;;
            esac
          done

          if [ $ERRORS -gt 0 ]; then
            echo "::error::Found $ERRORS sensitive file(s)"
            exit 1
          fi

      # Optional: Run full Bosun audit (requires API key)
      - name: Run Bosun Audit
        if: ${{ env.ANTHROPIC_API_KEY != '' }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          SCOPE="${{ github.event.inputs.scope || 'security' }}"
          echo "Running Bosun audit with scope: $SCOPE"

          # Run audit (adjust command based on actual CLI)
          # claude-code /audit $SCOPE || true

          echo "::notice::Bosun audit would run here with scope: $SCOPE"
          echo "Configure ANTHROPIC_API_KEY secret to enable full audits"

      # Upload findings as artifact
      - name: Upload findings
        if: always() && hashFiles('.bosun/findings.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: bosun-findings
          path: .bosun/findings.json
          retention-days: 30

      # Comment on PR with findings summary
      - name: Comment on PR
        if: github.event_name == 'pull_request' && hashFiles('.bosun/findings.json') != ''
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            try {
              const findings = JSON.parse(fs.readFileSync('.bosun/findings.json', 'utf8'));
              const summary = findings.summary || {};

              let body = '## Bosun Audit Results\n\n';
              body += `| Severity | Count |\n`;
              body += `|----------|-------|\n`;
              body += `| Critical | ${summary.bySeverity?.critical || 0} |\n`;
              body += `| High | ${summary.bySeverity?.high || 0} |\n`;
              body += `| Medium | ${summary.bySeverity?.medium || 0} |\n`;
              body += `| Low | ${summary.bySeverity?.low || 0} |\n`;
              body += `\n**Total**: ${summary.total || 0} findings\n`;

              if (findings.findings?.length > 0) {
                body += `\n### Top Findings\n\n`;
                const topFindings = findings.findings.slice(0, 5);
                for (const f of topFindings) {
                  body += `- **[${f.id}]** ${f.title} (${f.severity})\n`;
                }
                if (findings.findings.length > 5) {
                  body += `\n_...and ${findings.findings.length - 5} more_\n`;
                }
              }

              body += `\n---\n_Generated by [Bosun](https://github.com/curphey/bosun)_`;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            } catch (e) {
              console.log('No findings to report or error parsing:', e.message);
            }

  # Security-focused checks (always runs, no API needed)
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check for vulnerable dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm audit --audit-level=high || true
          fi
          if [ -f "yarn.lock" ]; then
            yarn audit --level high || true
          fi
          if [ -f "requirements.txt" ]; then
            pip install safety 2>/dev/null && safety check -r requirements.txt || true
          fi
